---
language: node_js

cache:
  directories:
    - node_modules

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/761be30e6a3158a118c2
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
